modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
    modId="kubejs_lcae"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    authors="gisellevonbingen"
    logoFile="icon.png"
    description='''${mod_description}'''

[[dependencies.kubejs_lcae]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.kubejs_lcae]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_api_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kubejs_lcae]]
    modId="kubejs"
    mandatory=true
    versionRange="[${kubejs_version},)"
    ordering="AFTER"
    side="BOTH"
